-- Remove the old unique constraints on CODIGO since we now allow BACKUP duplicates.
-- Validation is enforced at the application level.
-- This migration cleans up old constraints if they exist.
ALTER TABLE PRINTERS DROP CONSTRAINT IF EXISTS UKDTAGT763ULUWKV08CIDT7BUJ5;
ALTER TABLE PRINTERS DROP CONSTRAINT IF EXISTS UKDTAGT763ULUWKV08CIDT7BUJ5_INDEX_3;
ALTER TABLE PRINTERS DROP CONSTRAINT IF EXISTS UK_PRINTERS_CODIGO;
ALTER TABLE PRINTERS DROP CONSTRAINT IF EXISTS UK_PRINTERS_CODIGO_STATUS;
